### PR TITLE
fix a typo

### PR DESCRIPTION
**Pull request by bjmoran**

### CODE REVIEW

**Comment by brianmay** [comment]
Any assistance in diagnosing the test failures would be appreciated. Seems to be complaining that factory-boy is not installed, but as far as I can tell, a known good version of factory boy is installed.

**Comment by brianmay** [comment]
Oh, wonderful. Looks like due to the Faker package being renamed, old versions of factory-boy are now broken. Hopefully a new factory-boy should fix this.

**Comment by brianmay** [comment]
Fingers crossed. https://travis-ci.org/Karaage-Cluster/karaage/builds/189131306 from d08e7806c88d80e245019c12ec71474cd9a541eb should fix failing checks. Unfortunately won't help these pull requests unless they are rebased.

**Comment by bjmoran** [comment]
Thanks for fixing the factory-boy problem and for merging this pull request!

**Pull request merged**
