### PR TITLE
added invite_csv_users.py for cli bulk inviting

### PR DESCRIPTION
**Pull request by DanielTosello**
Adapted from import_csv_users.py

### CODE REVIEW

**Comment by brianmay** [comment]
isort errors. Should be easy to fix. Otherwise I can fix these for you if you want.

**Comment by DanielTosello** [comment]
I'm not sure how at this stage, so it'd be a big help. I'll watch over your
shoulder.

**Comment by DanielTosello** [comment]
Never mind, i worked it out... update incoming soon.

**Comment by brianmay** [comment]
Thanks for this.

**Pull request merged**
