### PR TITLE
find training accounts with Person.objects.all() instead of Person.ac…

### PR DESCRIPTION
**Pull request by bjmoran**
…tive.all()

this is needed if training accounts are system users

### CODE REVIEW

**Comment by brianmay** [comment]
Errr... Why should training accounts be system users? The intent was that system users are only for robots, not real people.

**Comment by bjmoran** [comment]
We made our training accounts system users so that they could all have the same email address. Is there a way to do that with regular users?

I've now rebased my branch and the checks are passing. Thanks for reviewing this.

**Comment by brianmay** [comment]
Something weird is going on with your rebase attempts. The rebase works, but then you merge in the old version which in defeats the point. Your pull requests end up with multiple versions of same commits. Maybe the error when you ``git push`` is confusing you - this is one case where you need to use ``git push -f`` (gerrit is better than github pull requests in this way).

Anyway, I am going to merge this. I am not sure about using system user's, but then again the point of system user's was that email addresses could be duplicated. So unless we can come up with a better solution, this will have to do for now.

**Comment by brianmay** [comment]
Oh, somehow I got confused in my code review. Why did you replace:

```
query.filter(username__startswith=training_prefix)		
```

With:

```
query = query.filter(username__iregex=training_prefix)
```

This seems a significant change...

**Comment by brianmay** [comment]
No comment to the above? Should I revert the change? Or was it deliberate?

**Comment by bjmoran** [comment]
Hi @brianmay, sorry to not reply earlier. You're correct that there is no need to change from `username__startswith` to `username__iregex`. Please revert to the old method.

Apologies also for the rebase problems. I'll need to revise how to do this next time. Thanks for merging.

**Comment by bjmoran** [comment]
Hi @brianmay, sorry about this confusion. I just tested this with both `startswith` and `iregex`.

`kg-manage lock_training_accounts` failed to lock open accounts when using `startswith`, but worked with `iregex`.

`kg-manage unlock_training_accounts` failed to unlock accounts when using `startswith`, but worked with `iregex`.

So we did need this change.

Apologies also for the rebase problems. I'll need to revise how to do this next time. Thanks for merging.

**Comment by brianmay** [comment]
Why the difference? Maybe ``istartswith`` would be better? You shouldn't be using regexp matching unless there is a good reason.

**Comment by brianmay** [comment]
My understanding is that all your training accounts are prefixed with with train. You probably don't want to match any account that happens to have "train" somewhere in the text.

Unless of course your training prefix really has been formatted as a regexp, e.g. (not tested):

TRAINING_ACCOUNT_PREFIX=r'^train\d+$$'

However this changes the meaning of the setting, and everyone using this would have to change.

**Comment by bjmoran** [comment]
This is what we have in /etc/karaage3/settings.py:

```
# Prefix for training accounts:
TRAINING_ACCOUNT_PREFIX = "^train[0-9]"
```

So that may explain why `iregex` worked and `startswith` did not.

Perhaps we should adjust that line to a simple string?
eg. `TRAINING_ACCOUNT_PREFIX = "train"`

**Comment by brianmay** [comment]
bjmoran <notifications@github.com> writes:

> This is what we have in /etc/karaage3/settings.py:
>
> ```
> # Prefix for training accounts:
> TRAINING_ACCOUNT_PREFIX = "^train[0-9]"
> ```
>
> So that may explain why `iregex` worked and `startswith` did not.
>
> Perhaps we should adjust that line to a simple string?
> eg. `TRAINING_ACCOUNT_PREFIX = "train"`

How very odd. Wonder how this every worked. Yes, your are right,
probably best to keep it as a regexp, and probably change the default
value to use a regexp too.

(looks like github issue tracker is broken and won't let me leave
responses; lets see if emails work...)
-- 
Brian May <brian@linuxpenguins.xyz>
https://linuxpenguins.xyz/brian/

**Comment by bjmoran** [comment]
Thanks for sorting this out!

**Pull request merged**
