### PR TITLE
Add sign up completion email

### LINKED ISSUE #802: Feature Request: Signup completion email
We recently started on a user admin workflow review. Mostly our workflows work really well, but the admin team picked out one sticking point - when a user is directed to karaage to do the initial signup process (as opposed to, say, our webpage with directions on how to use the service) there's nothing at the end of that process to tell them what to do next.

As such, the appropriate fix seems to be to add another email that gets sent after the completion of the initial password reset... of course, this requires a little refactoring of existing stuff, and splits password resets into two categories. We probably also, as part of that, want to add some interface to allow admins to edit templates from the application frontend... also aware it may need this pushed to the db as the existing templates are part of the deployment. 

Wanted to run it by you before I started making changes.

### PR DESCRIPTION
**Pull request by brianmay**
Fixes #802

Notes this does not include the email template yet.

### CODE REVIEW

**Comment by brianmay** [comment]
Ignore the build failure. Apparently Microsoft does not know how to create a reliable apt repository yet :-(

```
 Err:22 https://packages.microsoft.com/ubuntu/18.04/prod bionic/main amd64 Packages
  File has unexpected size (129084 != 128880). Mirror sync in progress? [IP: 13.90.21.104 443]
  Hashes of expected file:
   - Filesize:128880 [weak]
   - SHA512:1efddff25021ac53b4710ba4ae97c38faed3cf40ca7c32d30a064f997f9c28732ead02e52d34f266dbefc59a9a34760b5d85ed1c9a223d1f6d2c3616fd139658
   - SHA256:f8c839d306df54d68365ccd0238dfd90d978bd0b7e18f77de3a301a514b1713f
   - SHA1:945b754c2d1f7299d4219efd378c6b1a15f56bec [weak]
   - MD5Sum:c97ad3a1e8b48f125c79588119cd8a0f [weak]
  Release file created at: Mon, 17 Aug 2020 17:08:46 +0000
```

**Comment by brianmay** [comment]
Will see if this build comes good by itself. Otherwise might have to resort to a hack similar to https://github.com/dic-iit/bipedal-locomotion-framework/pull/10

**Comment by brianmay** [comment]
Template needs to be written still. Use following files as source:

* `karaage/plugins/kgapplications/templates/kgapplications/emails/common_approved_body.txt`
* `karaage/plugins/kgapplications/templates/kgapplications/emails/common_approved_subject.txt`

New files needed are (not tested):

* `karaage/plugins/kgapplications/templates/kgapplications/emails/common_completed_body.txt`
* `karaage/plugins/kgapplications/templates/kgapplications/emails/common_completed_subject.txt`

Noting that the `created_person` and `created_account` context variables have been replaced by a `has_usable_password` variables.

`has_usable_password` might be misleading actually - all users have usable passwords at this stage, probably should change that to `did_have_usable_password` or something...

**Comment by brianmay** [comment]
In working more on this, I noticed bug #861 which I have now fixed (but not yet deployed).

How does the proposed patch look?

**Comment by DanielTosello** [comment]
Haha whoops :) 
Patch looks good to me.

**Pull request merged**
